### ISSUE TITLE
Request for Edits

### ISSUE THREAD

**Issue by BridgedZone** [klinbee/Flattened-Dimensions#3]
Hello! I stumbled across this datapack yesterday while I was searching for a superflat datapack that'd also retain the water in aquatic biomes like oceans and rivers, as all other superflat datapacks I've tried would just turn those biomes into barren empty plains, and yours does exactly what I've been looking for! If it wouldn't be too much to ask, I'd like if you could possibly make some edits to both the Flat Dimensions datapacks (both the one with and without caves) for me or show me how to make these edits myself, as I'm not sure what to edit to get each datapack to do what I'd like to change.

For the version without caves, I noticed a strange inconsistency while I was testing both this datapack and the version with caves. I use another datapack called Geophilic that adds extra decor to most overworld biomes like these spikes in Stony Shore biomes shown below, and these generate like normal when using the version with caves.
![2024-04-22_22 49 12](https://github.com/Quidvio/Flattened-Dimensions/assets/167873329/73862893-88e0-4e4d-88cb-a1552963c661)
However, these don't generate when using the version without caves for some reason as you can see here:
![2024-04-22_22 51 25](https://github.com/Quidvio/Flattened-Dimensions/assets/167873329/f2d283e9-c8de-402f-b6a3-22b585e6dd3b)
To try and fix this, I tried using your No Caves datapack alongside the Flat Dimensions datapack with caves, and this fixes surface features like the stone spikes not generating. However, this then causes Ancient Cities to not generate at all for some reason. I'm assuming the simplest fix would be to take the version with caves and disable cave generation while retaining whatever code is allowing for surface features to still generate that isn't present in the version without caves, but I'm not sure what files to modify to do this. Could you help me figure this out?

And for the version with caves, could you help me make an edit to it that incorporates your Retro Caves datapack so that only the old caves and ravines will generate? I much prefer the old caves from a Survival standpoint as lighting up the new caves can be a bit of a chore, but attempting to use Retro Caves alongside Flat Dimensions with Caves results in the same bug I ran into when I tried using the No Caves datapack alongside it where Ancient Cities won't generate at all.

If it wouldn't be too much to ask, could we also make it so both these edited datapacks only affect the overworld instead of affecting all 3 dimensions? I've been using a datapack that affects the End dimension called Nullscape for a while and trying to use both it and either version of Flat Dimensions results in a game crash once the Ender Dragon is defeated as I found out while I was initially testing both datapacks yesterday, so ideally I'd like for just the overworld to be flat if possible. 

Thank you for your time!

**Comment by klinbee** [comment]
Wow, thank you for pointing this out to me. There are two ways to remove carver caves. 1. Overwrite the biome file (as they are placed on biome, like surface features) or 2. Set the carver probability itself to 0. 

For *some reason* I guess I hadn't learned about method 2. whenever I made this data pack originally, so I am currently just replacing the biome file with a default one that has no carvers. Which means that any modded changes get overwritten.

I'll get to this later today (as I also need to start updating for 1.20.5 and am busy as well) but yeah if you want an immediate fix, delete the `data/minecraft/worldgen/biome` folder entirely from Flattened Dimensions, and that adds back the carver caves (old caves) AND allows modded biome feature changes.

To do the dimension thing, all you need to do is delete `data/minecraft/worldgen/noise_settings/end.json` and `nether.json`. You also definitely want to delete `data/minecraft/worldgen/structure/bastion_remnant.json` and `data/minecraft/worldgen/placed_feature` folder entirely so that these features/structures in the nether/end generate at normal y-levels (there are no overworld features in the `placed_feature` file).

**Comment by BridgedZone** [comment]
Thanks for responding so soon with a quick fix! I've gone and edited the base version of Flat Dimensions with your immediate fix and the modded surface features now properly generate again, with the added bonus of there being only the old caves and ravines generating below the surface. As a sidenote, one extra thing that also had to be removed that wasn't mentioned in your step process was the `glowstone_extra.json` file in the `data/minecraft/worldgen/configured_feature` folder. Leaving this file results in the desired vanilla nether dimension but filled with all the extra chunks of Glowstone floating around so it's definitely important to remove that file/folder too as part of making the datapack only affect the overworld.

Aside from that, yeah the immediate fix worked perfectly and I now have a version of the datapack that only affects the overworld with all the modded surface features and the desired old caves only, so the version with caves is all done and the only thing left that I'd like is a version of the datapack with no caves as well if possible. Thanks again for your responding so quickly with that immediate fix!

**Comment by klinbee** [comment]
I have officially updated all versions to 1.20.5 and fixed the cave/biome incompatibility thing! Thanks for bringing this up.

Additionally, because of the new cave fix, you'll need to delete `data/minecraft/worldgen/configured_carver/nether_cave.json` to stop it from removing nether caves.
