### ISSUE TITLE
Nether

### ISSUE THREAD

**Issue by Noahg148** [klinbee/Flattened-Dimensions#5]
How to make the nether generate with the top layer of bedrock?

I am playing Flattened Dimensions mod V1.2.2.

Thanks for your help.

**Comment by klinbee** [comment]
@Noah-Goeminne take a look at the other branch in this repo, someone else had a request for it.

I'll take a look at the bug sometime later today.

**Comment by klinbee** [comment]
Turns out it was a stupid and complicated bug lol. I made a partial solution, the only parity issue is that they generate in lava now too. There is a way to fix that, but it would be even more stupid and complicated to fix, and would significantly slow down worldgen, so I'm not going to change that until Mojang fixes structure generation properly. Uploading new version now.
